import { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by user",
};

const HomeLayout = async ({ children }: { children: ReactNode }) => {
  return <>{children}</>
};

export default HomeLayout;
