import { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "HomeLayout",
  description: "Generated by user",
};

const HomeLayout = async ({ children }: { children: ReactNode }) => {
  return (
    <div>
      HomeLayout
      <br />
      {children}
    </div>
  );
};

export default HomeLayout;
